/// Groth16 zkSNARK Proof Verifier
///
/// Verifies zero-knowledge proofs on-chain using the BN254 (alt_bn128) curve.
/// The verification key is generated from the trusted setup and hardcoded
/// in vk.rs (generated by scripts/gen_verifier.js).
///
/// For devnet: uses a simplified verification stub.
/// For mainnet: will use ark-groth16 with the full pairing check.

use anchor_lang::prelude::*;

/// Verify a Groth16 proof against public inputs
///
/// In production, this performs the full pairing check:
///   e(A, B) = e(alpha, beta) * e(sum(vk_i * input_i), gamma) * e(C, delta)
///
/// For devnet testing, this is a stub that validates proof format.
/// The actual verification will be enabled once circuits are compiled
/// and the verification key is generated.
pub fn verify_proof(
    proof_a: &[u8],
    proof_b: &[u8],
    proof_c: &[u8],
    public_inputs: &[Vec<u8>],
) -> Result<bool> {
    // Validate proof dimensions
    // G1 points (A, C) = 64 bytes each (32 bytes x, 32 bytes y)
    // G2 point (B) = 128 bytes (2x 32 bytes for each coordinate)
    require!(proof_a.len() == 64, SpectreVerifierError::InvalidProofA);
    require!(proof_b.len() == 128, SpectreVerifierError::InvalidProofB);
    require!(proof_c.len() == 64, SpectreVerifierError::InvalidProofC);

    // Validate we have the expected public inputs:
    // [root, nullifier_hash, recipient, relayer, fee]
    require!(
        public_inputs.len() == 5,
        SpectreVerifierError::InvalidPublicInputs
    );

    // ──────────────────────────────────────────────
    // DEVNET STUB: Accept all well-formed proofs
    // TODO: Implement full Groth16 verification with:
    //   1. Deserialize proof points (A, B, C) from bytes
    //   2. Deserialize public inputs as field elements
    //   3. Load verification key from vk.rs
    //   4. Compute the pairing check
    //   5. Return true iff the pairing equation holds
    //
    // Implementation will use ark-bn254 and ark-groth16:
    //
    //   let pvk = prepare_verifying_key(&vk);
    //   let proof = Proof::<Bn254> {
    //       a: G1Affine::deserialize(&proof_a)?,
    //       b: G2Affine::deserialize(&proof_b)?,
    //       c: G1Affine::deserialize(&proof_c)?,
    //   };
    //   let inputs: Vec<Fr> = public_inputs.iter()
    //       .map(|i| Fr::from_le_bytes_mod_order(i))
    //       .collect();
    //   Groth16::<Bn254>::verify_with_processed_vk(&pvk, &inputs, &proof)
    //
    // ──────────────────────────────────────────────

    msg!("SPECTRE verifier: proof format valid (devnet stub)");

    // Check proof points are not zero (basic sanity)
    let a_nonzero = proof_a.iter().any(|&b| b != 0);
    let b_nonzero = proof_b.iter().any(|&b| b != 0);
    let c_nonzero = proof_c.iter().any(|&b| b != 0);

    if !a_nonzero || !b_nonzero || !c_nonzero {
        msg!("SPECTRE verifier: zero proof point detected");
        return Ok(false);
    }

    // DEVNET: Return true for well-formed proofs
    // MAINNET: Return result of actual pairing check
    Ok(true)
}

#[error_code]
pub enum SpectreVerifierError {
    #[msg("Invalid proof point A (expected 64 bytes)")]
    InvalidProofA,

    #[msg("Invalid proof point B (expected 128 bytes)")]
    InvalidProofB,

    #[msg("Invalid proof point C (expected 64 bytes)")]
    InvalidProofC,

    #[msg("Invalid public inputs count")]
    InvalidPublicInputs,

    #[msg("Proof verification failed")]
    VerificationFailed,
}
