/**
 * SPECTRE Verification Key Generator
 * 
 * Converts the snarkjs verification key (JSON) into a Rust module
 * that can be used for on-chain Groth16 proof verification.
 * 
 * Usage:
 *   node scripts/gen_verifier.js \
 *     --vk circuits/build/verification_key.json \
 *     --out programs/spectre/src/vk.rs
 */

const fs = require('fs');
const path = require('path');

const args = process.argv.slice(2);
function getArg(name, defaultVal) {
  const idx = args.indexOf(`--${name}`);
  return idx !== -1 && args[idx + 1] ? args[idx + 1] : defaultVal;
}

const VK_PATH = getArg('vk', path.join(__dirname, '..', 'circuits', 'build', 'verification_key.json'));
const OUT_PATH = getArg('out', path.join(__dirname, '..', 'programs', 'spectre', 'src', 'vk.rs'));

function main() {
  console.log('[SPECTRE] Generating Rust verifier module...');

  let vk;
  try {
    vk = JSON.parse(fs.readFileSync(VK_PATH, 'utf-8'));
  } catch (e) {
    console.error(`[!] Could not read verification key from ${VK_PATH}`);
    console.error('    Run: cd circuits && ./build.sh');
    
    // Generate initial vk.rs for devnet
    console.log('[*] Generating initial vk.rs for devnet...');
    const initial = generateInitialVk();
    fs.writeFileSync(OUT_PATH, initial);
    console.log(`[*] Initial vk.rs written to ${OUT_PATH}`);
    return;
  }

  const rust = generateRustModule(vk);
  fs.writeFileSync(OUT_PATH, rust);
  console.log(`[✓] Verifier module written to ${OUT_PATH}`);
}

function generateRustModule(vk) {
  const formatPoint = (p) => {
    if (Array.isArray(p[0])) {
      // G2 point: [[x1, x2], [y1, y2]]
      return `[
        [${p[0].map(v => `"${v}"`).join(', ')}],
        [${p[1].map(v => `"${v}"`).join(', ')}],
    ]`;
    }
    // G1 point: [x, y]
    return `["${p[0]}", "${p[1]}"]`;
  };

  return `/// SPECTRE Verification Key
/// Auto-generated by scripts/gen_verifier.js
/// DO NOT EDIT MANUALLY

/// Verification key for the SPECTRE Groth16 circuit
pub struct VerificationKey {
    pub alpha: [[&'static str; 2]; 1],
    pub beta: [[[&'static str; 2]; 2]; 1],
    pub gamma: [[[&'static str; 2]; 2]; 1],
    pub delta: [[[&'static str; 2]; 2]; 1],
    pub ic: Vec<[&'static str; 2]>,
}

pub fn get_vk() -> VerificationKey {
    VerificationKey {
        alpha: [${formatPoint(vk.vk_alpha_1)}],
        beta: [${formatPoint(vk.vk_beta_2)}],
        gamma: [${formatPoint(vk.vk_gamma_2)}],
        delta: [${formatPoint(vk.vk_delta_2)}],
        ic: vec![
${vk.IC.map(p => `            ${formatPoint(p)},`).join('\n')}
        ],
    }
}
`;
}

function generateInitialVk() {
  return `/// SPECTRE Verification Key
///
/// Generate the verification key by running:
///   cd circuits && ./build.sh
///   node scripts/gen_verifier.js

pub struct VerificationKey;

pub fn get_vk() -> VerificationKey {
    VerificationKey
}
`;
}

main();
